service: serverless-2024-aws-v2
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: ""

  environment:
    DB_ENDPOINT: ""
    DB_PORT: 3306
    DB_USER: ""
    DB_PASSWORD: ""
    DB_NAME: ""

  httpApi:
    cors: true

functions:

  getAllPatients:
    handler: src/handler.getAllPatients
    events:
      - httpApi:
          path: /getAllPatients
          method: GET
    
  getPatientById:
    handler: src/handler.getPatientById
    events:
      - httpApi:
          path: /getPatientById/{id}
          method: GET

  createPatient:
    handler: src/handler.createPatient
    events:
      - httpApi:
          path: /createPatient
          method: POST

  updatePatient:
    handler: src/handler.updatePatient
    events:
      - httpApi:
          path: /updatePatient/{id}
          method: PUT

  deletePatient:
    handler: src/handler.deletePatient
    events:
      - httpApi:
          path: /deletePatient/{id}
          method: DELETE

  debugEvent:
    handler: src/handler.debugEvent
    events:
      - httpApi:
          path: /debugEvent/{id}
          method: GET

plugins:
  - serverless-offline
  - serverless-plugin-typescript