service: serverless-2024-aws-v2
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: arn:aws:iam::590183771822:role/LabRole

  environment:
    DB_ENDPOINT: "db-afp-2024.cvq2w8w6chwy.us-east-1.rds.amazonaws.com"
    DB_PORT: 3306
    DB_USER: "admin"
    DB_PASSWORD: "password12345"
    DB_NAME: "afp_ps"

  httpApi:
    cors: true

functions:

  getAllPatients:
    handler: src/handler_ps.getAllPatients
    events:
      - httpApi:
          path: /getAllPatients
          method: GET
    
  getPatientById:
    handler: src/handler_ps.getPatientById
    events:
      - httpApi:
          path: /getPatientById/{id}
          method: GET

  createPatient:
    handler: src/handler_ps.createPatient
    events:
      - httpApi:
          path: /createPatient
          method: POST

  updatePatient:
    handler: src/handler_ps.updatePatient
    events:
      - httpApi:
          path: /updatePatient/{id}
          method: PUT

  deletePatient:
    handler: src/handler_ps.deletePatient
    events:
      - httpApi:
          path: /deletePatient/{id}
          method: DELETE

  debugEvent:
    handler: src/handler_ps.debugEvent
    events:
      - httpApi:
          path: /debugEvent/{id}
          method: GET

plugins:
  - serverless-offline
  - serverless-plugin-typescript